// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://kgtv3yqagngybbnjw2rgpkezaq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jui53vsznfbmlnu2irleuu6dve",
    "aws_cognito_identity_pool_id": "us-west-2:0b8f1acc-a685-4541-ad69-2c88dd21e5a2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_06g5LreVl",
    "aws_user_pools_web_client_id": "kkmsvfjefu9gh5bd2loomr4ea"
};


export default awsmobile;
